//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModelBuilder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Connections string from Clio settings.
        /// </summary>
        internal static string buildingMessage {
            get {
                return ResourceManager.GetString("buildingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DETAIL].
        /// </summary>
        internal static string detailTag {
            get {
                return ResourceManager.GetString("detailTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR].
        /// </summary>
        internal static string errorTag {
            get {
                return ResourceManager.GetString("errorTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting, goodbye !.
        /// </summary>
        internal static string exitMessage {
            get {
                return ResourceManager.GetString("exitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found.
        /// </summary>
        internal static string fileNotFoundMessage {
            get {
                return ResourceManager.GetString("fileNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO].
        /// </summary>
        internal static string infoTag {
            get {
                return ResourceManager.GetString("infoTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Successful !!!.
        /// </summary>
        internal static string loginSuccessMessage {
            get {
                return ResourceManager.GetString("loginSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to get Entity Meta data... this might take a while !.
        /// </summary>
        internal static string metadataMessage {
            get {
                return ResourceManager.GetString("metadataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OK].
        /// </summary>
        internal static string okTag {
            get {
                return ResourceManager.GetString("okTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully obtained connection string....
        /// </summary>
        internal static string succesConnectionMessage {
            get {
                return ResourceManager.GetString("succesConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TRY].
        /// </summary>
        internal static string tryTag {
            get {
                return ResourceManager.GetString("tryTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sit tight I am working on it.
        /// </summary>
        internal static string waitMessage {
            get {
                return ResourceManager.GetString("waitMessage", resourceCulture);
            }
        }
    }
}
